[supervisord]
nodaemon=true
user=choreo
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nezha]
command=/dashboard/nezha-dashboard --config /data/config.yaml
directory=/dashboard
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nezha.log
stderr_logfile=/var/log/supervisor/nezha-error.log
environment=HOME="/home/choreo",USER="choreo"

[program:cloudflared]
command=/usr/local/bin/cloudflared tunnel run --no-autoupdate --token %(ENV_TUNNEL_TOKEN)s
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/cloudflared.log
stderr_logfile=/var/log/supervisor/cloudflared-error.log
